[package]
name = "sorting"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "selection_sort"
path = "src/selection_sort.rs"

[[bin]]
name = "bubble_sort"
path = "src/bubble_sort.rs"

[[bin]]
name = "insertion_sort"
path = "src/insertion_sort.rs"
